[2024-06-17T16:54:49.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T16:54:49.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_dbt_execute.create_lineage_graph manual__2024-06-17T16:54:25.270424+00:00 [queued]>
[2024-06-17T16:54:49.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_dbt_execute.create_lineage_graph manual__2024-06-17T16:54:25.270424+00:00 [queued]>
[2024-06-17T16:54:49.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-17T16:54:50.017+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): create_lineage_graph> on 2024-06-17 16:54:25.270424+00:00
[2024-06-17T16:54:50.030+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-17T16:54:50.033+0000] {standard_task_runner.py:63} INFO - Started process 90 to run task
[2024-06-17T16:54:50.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'full_dbt_execute', 'create_lineage_graph', 'manual__2024-06-17T16:54:25.270424+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/full_dbt_execute.py', '--cfg-path', '/tmp/tmp5gfkc9qu']
[2024-06-17T16:54:50.036+0000] {standard_task_runner.py:91} INFO - Job 211: Subtask create_lineage_graph
[2024-06-17T16:54:50.072+0000] {task_command.py:426} INFO - Running <TaskInstance: full_dbt_execute.create_lineage_graph manual__2024-06-17T16:54:25.270424+00:00 [running]> on host 4c2406045e40
[2024-06-17T16:54:50.138+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_dbt_execute' AIRFLOW_CTX_TASK_ID='create_lineage_graph' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T16:54:25.270424+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T16:54:25.270424+00:00'
[2024-06-17T16:54:50.140+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T16:54:50.195+0000] {docker.py:366} INFO - Starting docker container from image custom_dbt_image
[2024-06-17T16:54:50.206+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-17T16:54:51.680+0000] {docker.py:436} INFO - [0m16:54:51  Running with dbt=1.5.0
[2024-06-17T16:54:51.804+0000] {docker.py:436} INFO - [0m16:54:51  Found 3 models, 4 tests, 0 snapshots, 0 analyses, 341 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics, 0 groups
[2024-06-17T16:54:51.805+0000] {docker.py:436} INFO - [0m16:54:51
[2024-06-17T16:54:52.178+0000] {docker.py:436} INFO - [0m16:54:52  Concurrency: 1 threads (target='dev')
[2024-06-17T16:54:52.180+0000] {docker.py:436} INFO - [0m16:54:52
[2024-06-17T16:54:52.311+0000] {docker.py:436} INFO - [0m16:54:52  Building catalog
[2024-06-17T16:54:57.497+0000] {docker.py:436} INFO - [0m16:54:57  Catalog written to /dbt_source/target/catalog.json
[2024-06-17T16:54:59.821+0000] {docker.py:436} INFO - [0m16:54:59  Running with dbt=1.5.0
[2024-06-17T16:54:59.962+0000] {docker.py:436} INFO - Serving docs at 8085
To access from your browser, navigate to: http://localhost:8085



Press Ctrl+C to exit.
