[2024-06-17T16:33:36.860+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T16:33:36.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_dbt_execute.create_lineage_graph manual__2024-06-17T16:33:19.936822+00:00 [queued]>
[2024-06-17T16:33:36.889+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_dbt_execute.create_lineage_graph manual__2024-06-17T16:33:19.936822+00:00 [queued]>
[2024-06-17T16:33:36.891+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-17T16:33:36.913+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): create_lineage_graph> on 2024-06-17 16:33:19.936822+00:00
[2024-06-17T16:33:36.928+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-17T16:33:36.930+0000] {standard_task_runner.py:63} INFO - Started process 74 to run task
[2024-06-17T16:33:36.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'full_dbt_execute', 'create_lineage_graph', 'manual__2024-06-17T16:33:19.936822+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/full_dbt_execute.py', '--cfg-path', '/tmp/tmpe82f52w3']
[2024-06-17T16:33:36.936+0000] {standard_task_runner.py:91} INFO - Job 207: Subtask create_lineage_graph
[2024-06-17T16:33:37.259+0000] {task_command.py:426} INFO - Running <TaskInstance: full_dbt_execute.create_lineage_graph manual__2024-06-17T16:33:19.936822+00:00 [running]> on host 204b6a35fe73
[2024-06-17T16:33:37.374+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_dbt_execute' AIRFLOW_CTX_TASK_ID='create_lineage_graph' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T16:33:19.936822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T16:33:19.936822+00:00'
[2024-06-17T16:33:37.377+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T16:33:37.470+0000] {docker.py:366} INFO - Starting docker container from image custom_dbt_image
[2024-06-17T16:33:37.651+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-17T16:33:43.197+0000] {docker.py:436} INFO - [0m16:33:43  Running with dbt=1.5.0
[2024-06-17T16:33:43.349+0000] {docker.py:436} INFO - [0m16:33:43  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 341 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2024-06-17T16:33:43.351+0000] {docker.py:436} INFO - [0m16:33:43
[2024-06-17T16:33:48.907+0000] {docker.py:436} INFO - [0m16:33:48  Concurrency: 1 threads (target='dev')
[2024-06-17T16:33:48.913+0000] {docker.py:436} INFO - [0m16:33:48
[2024-06-17T16:33:49.048+0000] {docker.py:436} INFO - [0m16:33:49  Building catalog
[2024-06-17T16:33:49.105+0000] {docker.py:436} INFO - [0m16:33:49  Catalog written to /dbt_source/target/catalog.json
[2024-06-17T16:33:52.924+0000] {docker.py:436} INFO - [0m16:33:52  Running with dbt=1.5.0
[2024-06-17T16:33:53.212+0000] {docker.py:436} INFO - Serving docs at 8085
To access from your browser, navigate to: http://localhost:8085



Press Ctrl+C to exit.
